version: '2.2'

services:
  php:
    build: .
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root1"
      MYSQL_DATABASE: "api_php_template"
